# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tonnam/proj/Intern/RS485/Modbus/Rebus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tonnam/proj/Intern/RS485/Modbus/Rebus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tonnam/proj/Intern/RS485/Modbus/Rebus/CMakeFiles /home/tonnam/proj/Intern/RS485/Modbus/Rebus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tonnam/proj/Intern/RS485/Modbus/Rebus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rebus_agent_v3

# Build rule for target.
rebus_agent_v3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rebus_agent_v3
.PHONY : rebus_agent_v3

# fast build rule for target.
rebus_agent_v3/fast:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/build
.PHONY : rebus_agent_v3/fast

src/control_server.o: src/control_server.cpp.o

.PHONY : src/control_server.o

# target to build an object file
src/control_server.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/control_server.cpp.o
.PHONY : src/control_server.cpp.o

src/control_server.i: src/control_server.cpp.i

.PHONY : src/control_server.i

# target to preprocess a source file
src/control_server.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/control_server.cpp.i
.PHONY : src/control_server.cpp.i

src/control_server.s: src/control_server.cpp.s

.PHONY : src/control_server.s

# target to generate assembly for a file
src/control_server.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/control_server.cpp.s
.PHONY : src/control_server.cpp.s

src/db_loader.o: src/db_loader.cpp.o

.PHONY : src/db_loader.o

# target to build an object file
src/db_loader.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/db_loader.cpp.o
.PHONY : src/db_loader.cpp.o

src/db_loader.i: src/db_loader.cpp.i

.PHONY : src/db_loader.i

# target to preprocess a source file
src/db_loader.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/db_loader.cpp.i
.PHONY : src/db_loader.cpp.i

src/db_loader.s: src/db_loader.cpp.s

.PHONY : src/db_loader.s

# target to generate assembly for a file
src/db_loader.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/db_loader.cpp.s
.PHONY : src/db_loader.cpp.s

src/epoll_loop.o: src/epoll_loop.cpp.o

.PHONY : src/epoll_loop.o

# target to build an object file
src/epoll_loop.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/epoll_loop.cpp.o
.PHONY : src/epoll_loop.cpp.o

src/epoll_loop.i: src/epoll_loop.cpp.i

.PHONY : src/epoll_loop.i

# target to preprocess a source file
src/epoll_loop.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/epoll_loop.cpp.i
.PHONY : src/epoll_loop.cpp.i

src/epoll_loop.s: src/epoll_loop.cpp.s

.PHONY : src/epoll_loop.s

# target to generate assembly for a file
src/epoll_loop.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/epoll_loop.cpp.s
.PHONY : src/epoll_loop.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/metrics.o: src/metrics.cpp.o

.PHONY : src/metrics.o

# target to build an object file
src/metrics.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/metrics.cpp.o
.PHONY : src/metrics.cpp.o

src/metrics.i: src/metrics.cpp.i

.PHONY : src/metrics.i

# target to preprocess a source file
src/metrics.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/metrics.cpp.i
.PHONY : src/metrics.cpp.i

src/metrics.s: src/metrics.cpp.s

.PHONY : src/metrics.s

# target to generate assembly for a file
src/metrics.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/metrics.cpp.s
.PHONY : src/metrics.cpp.s

src/modbus.o: src/modbus.cpp.o

.PHONY : src/modbus.o

# target to build an object file
src/modbus.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/modbus.cpp.o
.PHONY : src/modbus.cpp.o

src/modbus.i: src/modbus.cpp.i

.PHONY : src/modbus.i

# target to preprocess a source file
src/modbus.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/modbus.cpp.i
.PHONY : src/modbus.cpp.i

src/modbus.s: src/modbus.cpp.s

.PHONY : src/modbus.s

# target to generate assembly for a file
src/modbus.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/modbus.cpp.s
.PHONY : src/modbus.cpp.s

src/rebus_agent.o: src/rebus_agent.cpp.o

.PHONY : src/rebus_agent.o

# target to build an object file
src/rebus_agent.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/rebus_agent.cpp.o
.PHONY : src/rebus_agent.cpp.o

src/rebus_agent.i: src/rebus_agent.cpp.i

.PHONY : src/rebus_agent.i

# target to preprocess a source file
src/rebus_agent.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/rebus_agent.cpp.i
.PHONY : src/rebus_agent.cpp.i

src/rebus_agent.s: src/rebus_agent.cpp.s

.PHONY : src/rebus_agent.s

# target to generate assembly for a file
src/rebus_agent.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/rebus_agent.cpp.s
.PHONY : src/rebus_agent.cpp.s

src/rebus_frame.o: src/rebus_frame.cpp.o

.PHONY : src/rebus_frame.o

# target to build an object file
src/rebus_frame.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/rebus_frame.cpp.o
.PHONY : src/rebus_frame.cpp.o

src/rebus_frame.i: src/rebus_frame.cpp.i

.PHONY : src/rebus_frame.i

# target to preprocess a source file
src/rebus_frame.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/rebus_frame.cpp.i
.PHONY : src/rebus_frame.cpp.i

src/rebus_frame.s: src/rebus_frame.cpp.s

.PHONY : src/rebus_frame.s

# target to generate assembly for a file
src/rebus_frame.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/rebus_frame.cpp.s
.PHONY : src/rebus_frame.cpp.s

src/redis_connector.o: src/redis_connector.cpp.o

.PHONY : src/redis_connector.o

# target to build an object file
src/redis_connector.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/redis_connector.cpp.o
.PHONY : src/redis_connector.cpp.o

src/redis_connector.i: src/redis_connector.cpp.i

.PHONY : src/redis_connector.i

# target to preprocess a source file
src/redis_connector.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/redis_connector.cpp.i
.PHONY : src/redis_connector.cpp.i

src/redis_connector.s: src/redis_connector.cpp.s

.PHONY : src/redis_connector.s

# target to generate assembly for a file
src/redis_connector.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/redis_connector.cpp.s
.PHONY : src/redis_connector.cpp.s

src/tcp_broadcaster.o: src/tcp_broadcaster.cpp.o

.PHONY : src/tcp_broadcaster.o

# target to build an object file
src/tcp_broadcaster.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/tcp_broadcaster.cpp.o
.PHONY : src/tcp_broadcaster.cpp.o

src/tcp_broadcaster.i: src/tcp_broadcaster.cpp.i

.PHONY : src/tcp_broadcaster.i

# target to preprocess a source file
src/tcp_broadcaster.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/tcp_broadcaster.cpp.i
.PHONY : src/tcp_broadcaster.cpp.i

src/tcp_broadcaster.s: src/tcp_broadcaster.cpp.s

.PHONY : src/tcp_broadcaster.s

# target to generate assembly for a file
src/tcp_broadcaster.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/tcp_broadcaster.cpp.s
.PHONY : src/tcp_broadcaster.cpp.s

src/thread_pool.o: src/thread_pool.cpp.o

.PHONY : src/thread_pool.o

# target to build an object file
src/thread_pool.cpp.o:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/thread_pool.cpp.o
.PHONY : src/thread_pool.cpp.o

src/thread_pool.i: src/thread_pool.cpp.i

.PHONY : src/thread_pool.i

# target to preprocess a source file
src/thread_pool.cpp.i:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/thread_pool.cpp.i
.PHONY : src/thread_pool.cpp.i

src/thread_pool.s: src/thread_pool.cpp.s

.PHONY : src/thread_pool.s

# target to generate assembly for a file
src/thread_pool.cpp.s:
	$(MAKE) -f CMakeFiles/rebus_agent_v3.dir/build.make CMakeFiles/rebus_agent_v3.dir/src/thread_pool.cpp.s
.PHONY : src/thread_pool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rebus_agent_v3"
	@echo "... src/control_server.o"
	@echo "... src/control_server.i"
	@echo "... src/control_server.s"
	@echo "... src/db_loader.o"
	@echo "... src/db_loader.i"
	@echo "... src/db_loader.s"
	@echo "... src/epoll_loop.o"
	@echo "... src/epoll_loop.i"
	@echo "... src/epoll_loop.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/metrics.o"
	@echo "... src/metrics.i"
	@echo "... src/metrics.s"
	@echo "... src/modbus.o"
	@echo "... src/modbus.i"
	@echo "... src/modbus.s"
	@echo "... src/rebus_agent.o"
	@echo "... src/rebus_agent.i"
	@echo "... src/rebus_agent.s"
	@echo "... src/rebus_frame.o"
	@echo "... src/rebus_frame.i"
	@echo "... src/rebus_frame.s"
	@echo "... src/redis_connector.o"
	@echo "... src/redis_connector.i"
	@echo "... src/redis_connector.s"
	@echo "... src/tcp_broadcaster.o"
	@echo "... src/tcp_broadcaster.i"
	@echo "... src/tcp_broadcaster.s"
	@echo "... src/thread_pool.o"
	@echo "... src/thread_pool.i"
	@echo "... src/thread_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

